"""
Property-based tests for transformation-rule reversibility (issue #8).

Two distinct kinds of "reversibility" are tested here, because DC+/DC− and
ERA/INS sit differently in Dau's calculus:

1. ``DC+ ↔ DC−`` is a true *semantic equivalence pair*: double cuts cancel,
   so inserting then erasing them (or vice versa) yields a graph identical
   to the original. We test the structural round-trip directly.

2. ``ERA + INS`` are one-directional sound rules with opposite polarity
   requirements (ERA needs a positive area, INS needs a negative one) — they
   are *not* a soundness-preserving inverse pair in the same area. Issue
   #8's literal phrasing isn't directly realizable. What is realizable, and
   genuinely useful, is checking ERA's *mutation bookkeeping*: the result
   of ERA must equal the original EGI minus exactly the closure of the
   erased selection (no over-erasure, no under-erasure, no positional drift).
   The ``ERA-restore`` test exercises this: it removes a closed subgraph,
   then re-adds the same elements at the same positions, and asserts
   structural identity with the original. A failure here would surface as
   either ERA erasing too much (e.g. a shared identity vertex that should
   have remained semi-free) or its closure missing transitively required
   elements.

Both tests follow the seed-by-applying-rules pattern recommended in #8:
the input EGI is generated by parsing a well-formed EGIF, and the seed
strategy guarantees that preconditions hold by construction.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).parent))

import pytest
from frozendict import frozendict
from hypothesis import HealthCheck, assume, given, settings, strategies as st

from egi_core_dau import (
    AreaPolarity,
    Cut,
    Edge,
    ElementID,
    RelationalGraphWithCuts,
    Vertex,
)
from egif_parser_dau import parse_egif
from formal_transformation_rules import (
    DeiterationRule,
    DoubleCutErasureRule,
    DoubleCutInsertionRule,
    ErasureRule,
    IterationRule,
    TransformationContext,
)
from subgraph_closure_validator import SubgraphClosureValidator

from test_properties_round_trip import egif_sheet


# --------------------------------------------------------------------------- #
# Shared strategies                                                           #
# --------------------------------------------------------------------------- #


@st.composite
def _seed_egi(draw):
    """Parse a generated EGIF into an EGI. Skip empty or unparseable shapes."""
    text = draw(egif_sheet(max_atoms=3, max_cut_depth=1))
    try:
        egi = parse_egif(text)
    except Exception:
        assume(False)
        return None
    return egi


def _direct_area_contents(egi: RelationalGraphWithCuts, area_id: ElementID):
    """Direct contents of ``area_id`` (not recursive into nested cuts)."""
    return egi.area.get(area_id, frozenset())


def _is_positive_area(egi: RelationalGraphWithCuts, area_id: ElementID) -> bool:
    polarity, _ = egi.area_polarity(area_id)
    return polarity is AreaPolarity.POSITIVE


# --------------------------------------------------------------------------- #
# DC+ ↔ DC− structural round-trip                                             #
# --------------------------------------------------------------------------- #


@st.composite
def _dcplus_target(draw):
    """Generate ``(egi, target_area, selected_subgraph)`` for a DC+ application.

    DC+ has no polarity restriction. ``selected_subgraph`` may be empty (DC+
    encloses everything in the area in that case) or any subset of the area's
    *direct* contents.
    """
    egi = draw(_seed_egi())
    area_id = draw(st.sampled_from(list(egi.area.keys())))
    contents = list(_direct_area_contents(egi, area_id))
    if not contents:
        # DC+ on an empty area is degenerate; skip
        assume(False)
    selection = draw(st.sets(st.sampled_from(contents)))
    return egi, area_id, frozenset(selection)


class TestDoubleCutReversibility:
    """DC+ then DC− on the just-added outer cut reproduces the original EGI."""

    @settings(
        max_examples=120,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
    )
    @given(_dcplus_target())
    def test_dc_plus_minus_round_trip_is_structural_identity(self, params):
        egi, area_id, selection = params

        polarity, depth = egi.area_polarity(area_id)
        ctx_plus = TransformationContext(
            source_egi=egi,
            target_area=area_id,
            selected_subgraph=selection,
            area_polarity=polarity,
            nesting_depth=depth,
        )

        plus_result = DoubleCutInsertionRule().apply_transformation(ctx_plus)
        assert plus_result.success, f"DC+ failed: {plus_result.error_message}"
        g_plus = plus_result.result_egi
        outer_cut_id = ElementID(plus_result.changes_made["outer_cut"])

        # DC− on the outer cut should remove both added cuts.
        polarity2, depth2 = g_plus.area_polarity(area_id)
        ctx_minus = TransformationContext(
            source_egi=g_plus,
            target_area=area_id,
            selected_subgraph=frozenset([outer_cut_id]),
            area_polarity=polarity2,
            nesting_depth=depth2,
        )
        minus_result = DoubleCutErasureRule().apply_transformation(ctx_minus)
        assert minus_result.success, f"DC- failed: {minus_result.error_message}"
        g_final = minus_result.result_egi

        # Structural identity: every field of the EGI must equal the original.
        assert g_final.sheet == egi.sheet
        assert g_final.V == egi.V
        assert g_final.E == egi.E
        assert g_final.Cut == egi.Cut, (
            f"Cut mismatch: original={ {c.id for c in egi.Cut} } "
            f"final={ {c.id for c in g_final.Cut} }"
        )
        assert g_final.nu == egi.nu
        assert g_final.rel == egi.rel
        # ``area`` is a frozendict — compare as dicts.
        assert dict(g_final.area) == dict(egi.area), (
            f"area mismatch:\n  original={dict(egi.area)}\n  final={dict(g_final.area)}"
        )


# --------------------------------------------------------------------------- #
# ERA mutation reversibility                                                   #
# --------------------------------------------------------------------------- #


@st.composite
def _era_target(draw):
    """Generate ``(egi, positive_area, raw_selection)`` for an ERA application.

    Picks a positive area and draws a non-empty subset of its *direct*
    contents as the raw selection — ERA's precondition requires the
    selection itself (before closure expansion) to live in the target
    area's direct contents. The closure expansion that ERA performs
    internally may then pull in cut interiors and semi-free vertices from
    other areas; those are removed by ERA's mutation but are not part of
    the user-facing selection.

    The strategy filters to selections whose Beta-aware closure is in fact
    closed, so ERA's preconditions hold by construction.
    """
    egi = draw(_seed_egi())
    positive_areas = [a for a in egi.area.keys() if _is_positive_area(egi, a)]
    if not positive_areas:
        assume(False)
    area_id = draw(st.sampled_from(positive_areas))
    contents = list(_direct_area_contents(egi, area_id))
    if not contents:
        assume(False)
    selection = frozenset(
        draw(st.sets(st.sampled_from(contents), min_size=1))
    )

    # Match ERA's actual closure semantics (issue #9): for_erasure=True.
    validator = SubgraphClosureValidator(egi)
    analysis = validator.analyze_closure(
        selection, allow_expansion=True, context_area=area_id,
        for_erasure=True,
    )
    assume(analysis.is_closed)
    return egi, area_id, selection


def _restore_erased(
    g_after: RelationalGraphWithCuts,
    g_before: RelationalGraphWithCuts,
    erased: frozenset,
    target_area: ElementID,
) -> RelationalGraphWithCuts:
    """Re-add the erased closure to ``g_after`` using ``g_before`` as the
    source of truth for IDs, nu, rel, and area placement.

    This is the structural inverse of ERA's mutation, intentionally
    bypassing Dau's INS (whose polarity preconditions disallow re-insertion
    into a positive area). The point is to test that ERA's removal is
    bijective with the closure-set-difference.
    """
    new_V = set(g_after.V)
    new_E = set(g_after.E)
    new_Cut = set(g_after.Cut)
    new_nu = dict(g_after.nu)
    new_rel = dict(g_after.rel)
    new_area = {k: set(v) for k, v in g_after.area.items()}

    # Restore vertices / edges / cuts that were erased
    for v in g_before.V:
        if v.id in erased and not any(x.id == v.id for x in new_V):
            new_V.add(v)
    for e in g_before.E:
        if e.id in erased:
            if not any(x.id == e.id for x in new_E):
                new_E.add(e)
            new_nu[e.id] = g_before.nu[e.id]
            if e.id in g_before.rel:
                new_rel[e.id] = g_before.rel[e.id]
    for c in g_before.Cut:
        if c.id in erased and not any(x.id == c.id for x in new_Cut):
            new_Cut.add(c)

    # Restore area mapping for areas that existed before
    for area_id, contents in g_before.area.items():
        if area_id in erased:
            # Erased cut — restore its area entry verbatim
            new_area[area_id] = set(contents)
        else:
            # Preserved area — add back any erased elements that lived here
            restored_here = {e for e in contents if e in erased}
            new_area.setdefault(area_id, set()).update(restored_here)

    return RelationalGraphWithCuts(
        V=frozenset(new_V),
        E=frozenset(new_E),
        nu=frozendict(new_nu),
        sheet=g_after.sheet,
        Cut=frozenset(new_Cut),
        area=frozendict({k: frozenset(v) for k, v in new_area.items()}),
        rel=frozendict(new_rel),
    )


class TestErasureRestoreReversibility:
    """ERA's mutation is the structural inverse of re-adding the closure.

    This is a weaker claim than "ERA and INS are inverse rules" (they aren't,
    in Dau's calculus). It's a precise claim about ERA's bookkeeping:
    everything in the closure is removed, nothing else is, and re-inserting
    the same elements at the same positions reproduces the original EGI.
    """

    @settings(
        max_examples=120,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
    )
    @given(_era_target())
    def test_era_then_restore_is_structural_identity(self, params):
        egi, area_id, selection = params

        # Compute the closure expansion ERA will perform internally — this
        # is the exact set of element IDs ERA's mutation should remove.
        # Must mirror ERA's for_erasure=True (issue #9).
        validator = SubgraphClosureValidator(egi)
        analysis = validator.analyze_closure(
            selection, allow_expansion=True, context_area=area_id,
            for_erasure=True,
        )
        expected_erased = analysis.closed_subgraph

        polarity, depth = egi.area_polarity(area_id)
        ctx = TransformationContext(
            source_egi=egi,
            target_area=area_id,
            selected_subgraph=selection,
            area_polarity=polarity,
            nesting_depth=depth,
        )
        result = ErasureRule().apply_transformation(ctx)
        assert result.success, f"ERA failed: {result.error_message}"
        g_after = result.result_egi

        # ERA must have removed exactly the expanded closure.
        for v in g_after.V:
            assert v.id not in expected_erased, f"ERA left erased vertex {v.id}"
        for e in g_after.E:
            assert e.id not in expected_erased, f"ERA left erased edge {e.id}"
        for c in g_after.Cut:
            assert c.id not in expected_erased, f"ERA left erased cut {c.id}"

        # Restoring the erased closure to the same area must recover the original.
        g_restored = _restore_erased(g_after, egi, expected_erased, area_id)

        assert g_restored.sheet == egi.sheet
        assert g_restored.V == egi.V, (
            f"V mismatch after restore: original_minus_restored="
            f"{ {v.id for v in egi.V} - {v.id for v in g_restored.V} }"
        )
        assert g_restored.E == egi.E
        assert g_restored.Cut == egi.Cut
        assert g_restored.nu == egi.nu
        assert g_restored.rel == egi.rel
        assert dict(g_restored.area) == dict(egi.area), (
            f"area mismatch after restore:\n"
            f"  original={dict(egi.area)}\n  restored={dict(g_restored.area)}"
        )


# --------------------------------------------------------------------------- #
# IT+ ↔ IT− structural round-trip                                             #
# --------------------------------------------------------------------------- #


@st.composite
def _iter_target(draw):
    """Generate ``(egi, source_area, target_area, selection)`` for an IT+
    application that has a soundly-applicable IT− inverse.

    Strategy:
      - source area = sheet (positive depth 0)
      - target area = a cut directly inside the sheet (negative depth 1)
        — strictly deeper, so IT+ "extends a line of identity" rather than
        duplicating vertices.
      - selection = a non-empty subset of edges directly in the source.

    Cuts are excluded from the selection set to keep the seed simple; the
    rule supports iterating cuts but their recursive copy semantics add
    surface area beyond what this round-trip test needs to probe.
    """
    egi = draw(_seed_egi())

    sheet_contents = _direct_area_contents(egi, egi.sheet)
    edges_in_sheet = [
        eid for eid in sheet_contents if any(e.id == eid for e in egi.E)
    ]
    cuts_in_sheet = [
        cid for cid in sheet_contents if any(c.id == cid for c in egi.Cut)
    ]
    if not edges_in_sheet or not cuts_in_sheet:
        assume(False)

    selection = frozenset(
        draw(
            st.lists(
                st.sampled_from(edges_in_sheet),
                min_size=1,
                max_size=len(edges_in_sheet),
                unique=True,
            )
        )
    )
    target_cut = draw(st.sampled_from(cuts_in_sheet))

    return egi, egi.sheet, target_cut, selection


class TestIterationReversibility:
    """IT+ then IT− on the just-iterated copy reproduces the original EGI.

    Both rules are truth-preserving in Dau §14.4: IT+ is conjunction
    introduction (copy an asserted subgraph into a more deeply nested
    area, which a line of identity can extend into); IT− removes a
    subgraph whose isomorphic image exists in an enclosing area. They
    form a genuine equivalence pair, unlike ERA/INS.

    The seed-by-construction strategy guarantees the IT+ preconditions
    (destination strictly enclosed by source); the isomorphism
    precondition of IT− is then automatic — the original subgraph in
    the source area is the witness.
    """

    @settings(
        max_examples=120,
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
    )
    @given(_iter_target())
    def test_it_plus_minus_round_trip_is_structural_identity(self, params):
        egi, source_area, target_area, selection = params

        # Apply IT+: copy the selection from source_area into target_area.
        # target_area is strictly deeper, so vertices are reused (lines of
        # identity extend) and only edges get fresh IDs in the copy.
        polarity, depth = egi.area_polarity(target_area)
        ctx_plus = TransformationContext(
            source_egi=egi,
            target_area=target_area,
            selected_subgraph=selection,
            area_polarity=polarity,
            nesting_depth=depth,
        )
        plus_result = IterationRule().apply_transformation(ctx_plus)
        assume(plus_result.success)  # selection may be unreachable; skip
        g_plus = plus_result.result_egi

        # The IT+ copies are the new top-level elements added to
        # ``target_area``.  Restrict to elements actually present in
        # g_plus (defensive; the rule reports them via changes_made).
        copy_ids = frozenset(
            ElementID(s) for s in plus_result.changes_made.get("copied_elements", [])
        )
        present_ids = (
            {v.id for v in g_plus.V}
            | {e.id for e in g_plus.E}
            | {c.id for c in g_plus.Cut}
        )
        assume(copy_ids and copy_ids <= present_ids)

        # Apply IT− to remove just the copy.  IT− validates via the
        # isomorphism engine, which should find the original subgraph
        # in source_area as the enclosing witness.
        polarity2, depth2 = g_plus.area_polarity(target_area)
        ctx_minus = TransformationContext(
            source_egi=g_plus,
            target_area=target_area,
            selected_subgraph=copy_ids,
            area_polarity=polarity2,
            nesting_depth=depth2,
        )
        minus_result = DeiterationRule().apply_transformation(ctx_minus)
        assert minus_result.success, (
            f"IT- failed after IT+: {minus_result.error_message}"
        )
        g_final = minus_result.result_egi

        # Structural identity: every field equals the original.
        assert g_final.sheet == egi.sheet
        assert g_final.V == egi.V
        assert g_final.E == egi.E
        assert g_final.Cut == egi.Cut
        assert g_final.nu == egi.nu
        assert g_final.rel == egi.rel
        assert dict(g_final.area) == dict(egi.area), (
            f"area mismatch after IT+ → IT-:\n"
            f"  original={dict(egi.area)}\n  final={dict(g_final.area)}"
        )


# --------------------------------------------------------------------------- #
# Regression for issue #9 — fixed by for_erasure=True closure semantics       #
# --------------------------------------------------------------------------- #


def test_era_drags_descendant_area_edges_into_closure():
    """Regression for issue #9.

    Setup: EGIF ``(P *x) ~[ (Q x) ]`` —
      - vertex x and edge P live on the sheet (positive)
      - edge Q lives inside a cut (negative), referencing x

    Pre-fix: the Beta-aware closure expanded {x} to {x, P} only — Q was
    skipped as descendant-area, leading ERA to construct an EGI without
    x but with Q still referencing it. RelationalGraphWithCuts.
    __post_init__ then rejected the construction.

    Post-fix: ERA passes ``for_erasure=True`` to ``analyze_closure``,
    which pulls in every edge referencing the vertex regardless of area.
    Either ERA succeeds with the cut+Q also erased, or the closure
    expansion drags Q (and possibly the cut, if Q was the only thing in
    it) in and ERA proceeds correctly.
    """
    egi = parse_egif("(P *x) ~[ (Q x) ]")
    sheet_contents = egi.area[egi.sheet]
    vertex_ids = {v.id for v in egi.V}
    sheet_vertex = next(iter(sheet_contents & vertex_ids))

    polarity, depth = egi.area_polarity(egi.sheet)
    ctx = TransformationContext(
        source_egi=egi,
        target_area=egi.sheet,
        selected_subgraph=frozenset([sheet_vertex]),
        area_polarity=polarity,
        nesting_depth=depth,
    )
    result = ErasureRule().apply_transformation(ctx)
    assert result.success, f"ERA failed: {result.error_message}"

    # The vertex x must be gone, and so must Q (it referenced x).
    g = result.result_egi
    assert not any(v.id == sheet_vertex for v in g.V)
    assert all(g.rel.get(e.id) != "Q" for e in g.E), (
        f"Q edge survived erasure of its referent: {dict(g.rel)}"
    )


def test_suite():
    """Run all rule-reversibility property tests."""
    pytest.main([__file__, "-v"])


if __name__ == "__main__":
    test_suite()
