#!/usr/bin/env python3
"""
Generate Working Code Index - Auto-generate WHAT_WORKS_NOW.md

Scans the codebase and generates component status index:
- Categorizes modules by tier (Production/Stable/Experimental/Deprecated)
- Identifies import relationships
- Detects orphaned modules
- Lists protected core modules

USAGE:
    python tools/generate_working_code_index.py
    python tools/generate_working_code_index.py --output WHAT_WORKS_NOW.md
"""

import ast
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Set, Tuple, Optional
from collections import defaultdict
import argparse


class ComponentIndexer:
    """Generates component status index."""
    
    def __init__(self, project_root: Path = None):
        self.project_root = project_root or Path.cwd()
        self.src_path = self.project_root / "src"
        self.state_file = self.project_root / ".coherence_session_state.json"
        
        # Load session state for component tiers
        self.session_state = self._load_session_state()
        
        # Import tracking
        self.imports: Dict[str, Set[str]] = defaultdict(set)
        self.imported_by: Dict[str, int] = defaultdict(int)
        
    def _load_session_state(self) -> Dict:
        """Load session state for tier information."""
        if self.state_file.exists():
            with open(self.state_file, 'r') as f:
                return json.load(f)
        return {}
    
    def scan_imports(self) -> None:
        """Scan codebase for import relationships."""
        print("🔍 Scanning imports...")
        
        for py_file in self.src_path.rglob("*.py"):
            if "__pycache__" in str(py_file):
                continue
            
            try:
                with open(py_file, 'r', encoding='utf-8') as f:
                    tree = ast.parse(f.read(), filename=str(py_file))
                
                module_path = py_file.relative_to(self.src_path)
                module_name = str(module_path).replace('/', '.').replace('\\', '.')[:-3]
                
                for node in ast.walk(tree):
                    if isinstance(node, (ast.Import, ast.ImportFrom)):
                        if isinstance(node, ast.Import):
                            for alias in node.names:
                                imported = alias.name.split('.')[0]
                                self.imports[module_name].add(imported)
                                self.imported_by[imported] += 1
                        
                        elif isinstance(node, ast.ImportFrom) and node.module:
                            imported = node.module.split('.')[0]
                            self.imports[module_name].add(imported)
                            self.imported_by[imported] += 1
            
            except Exception:
                pass
        
        print(f"   Analyzed {len(self.imports)} modules")
    
    def get_protected_modules(self) -> List[str]:
        """Get list of protected core modules."""
        components = self.session_state.get("active_components", {})
        tier1 = components.get("production_tier1", {}).get("modules", [])
        
        # Extract just filenames
        protected = []
        for module_desc in tier1:
            if "PROTECTED" in module_desc:
                # Extract filename from "src/filename.py - Description (PROTECTED)"
                filename = module_desc.split()[0].split('/')[-1]
                protected.append(filename)
        
        return sorted(protected)
    
    def get_recent_commits(self, count: int = 5) -> List[str]:
        """Get recent git commits."""
        try:
            result = subprocess.run(
                ['git', 'log', f'-{count}', '--pretty=format:%h - %s (%ci)'],
                capture_output=True,
                text=True,
                cwd=self.project_root
            )
            
            if result.returncode == 0:
                commits = result.stdout.strip().split('\n')
                return [c for c in commits if c]
            
        except Exception:
            pass
        
        return []
    
    def generate_markdown(self) -> str:
        """Generate WHAT_WORKS_NOW.md content."""
        lines = [
            "# What Actually Works Right Now",
            "",
            f"**Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ",
            "**Auto-Generated**: This file is generated by `tools/generate_working_code_index.py`",
            "",
            "---",
            "",
            "## 🎯 Quick Reference",
            "",
            "Component status tiers:",
            "",
            "- **TIER 1 (Production)** ✅ - Use these confidently",
            "- **TIER 2 (Stable)** 🟢 - Safe to use",
            "- **TIER 3 (Experimental)** 🟡 - Use with caution",
            "- **TIER 4 (Deprecated)** 🔴 - Do not use",
            "- **TIER 5 (Not Integrated)** 📦 - Separate packages",
            "",
            "---",
            "",
        ]
        
        # Get component tiers from session state
        components = self.session_state.get("active_components", {})
        
        # Tier 1: Production
        tier1 = components.get("production_tier1", {})
        if tier1:
            lines.extend([
                "## TIER 1: Production Components ✅",
                "",
                tier1.get("description", "Production quality components"),
                "",
            ])
            
            for module in tier1.get("modules", []):
                lines.append(f"- **`{module}`**")
            
            lines.append("")
        
        # Tier 2: Stable
        tier2 = components.get("stable_tier2", {})
        if tier2:
            lines.extend([
                "## TIER 2: Stable Components 🟢",
                "",
                tier2.get("description", "Stable implementations"),
                "",
            ])
            
            for module in tier2.get("modules", []):
                lines.append(f"- **`{module}`**")
            
            lines.append("")
        
        # Tier 3: Experimental
        tier3 = components.get("experimental_tier3", {})
        lines.extend([
            "## TIER 3: Experimental Components 🟡",
            "",
        ])
        
        if tier3 and tier3.get("modules"):
            for module in tier3.get("modules", []):
                lines.append(f"- **`{module}`**")
        else:
            lines.append("*None currently - all active development completed or in stable tier*")
        
        lines.append("")
        
        # Tier 4: Deprecated
        tier4 = components.get("deprecated_tier4", {})
        if tier4 and tier4.get("modules"):
            lines.extend([
                "## TIER 4: Deprecated Components 🔴",
                "",
                "### DO NOT USE - Superseded",
                "",
            ])
            
            for module in tier4.get("modules", []):
                lines.append(f"- **`{module}`**")
            
            lines.append("")
        
        # Tier 5: Not Integrated
        tier5 = components.get("not_integrated", {})
        if tier5:
            lines.extend([
                "## TIER 5: Not Integrated 📦",
                "",
                tier5.get("description", "Separate packages not used in this project"),
                "",
            ])
            
            for module in tier5.get("modules", []):
                lines.append(f"- **`{module}`**")
            
            lines.append("")
        
        # Protected modules
        protected = self.get_protected_modules()
        if protected:
            lines.extend([
                "---",
                "",
                f"## 🔒 Protected Core Modules ({len(protected)} total)",
                "",
                "These modules require authorization to modify:",
                "",
            ])
            
            for i, module in enumerate(protected, 1):
                lines.append(f"{i}. `{module}`")
            
            lines.extend([
                "",
                "**To modify**: Set `export ARISBE_CORE_OVERRIDE=true`",
                "",
            ])
        
        # Test status
        test_status = self.session_state.get("test_status", {})
        if test_status:
            lines.extend([
                "---",
                "",
                "## 🧪 Test Status",
                "",
            ])
            
            for key, value in test_status.items():
                if key != "last_test_run":
                    label = key.replace('_', ' ').title()
                    lines.append(f"- **{label}**: {value}")
            
            if "last_test_run" in test_status:
                lines.append(f"- **Last Run**: {test_status['last_test_run']}")
            
            lines.append("")
        
        # Import relationships
        if self.imported_by:
            top_imported = sorted(
                [(name, count) for name, count in self.imported_by.items()],
                key=lambda x: x[1],
                reverse=True
            )[:10]
            
            if top_imported:
                lines.extend([
                    "---",
                    "",
                    "## 📊 Most Imported Modules",
                    "",
                ])
                
                for name, count in top_imported:
                    lines.append(f"- `{name}` ({count} imports)")
                
                lines.append("")
        
        # Recent changes
        recent_commits = self.get_recent_commits(5)
        if recent_commits:
            lines.extend([
                "---",
                "",
                "## 🚀 Recent Changes",
                "",
            ])
            
            for commit in recent_commits:
                # Format: hash - message (date)
                lines.append(f"- {commit}")
            
            lines.append("")
        
        # Usage instructions
        lines.extend([
            "---",
            "",
            "## 🎯 How to Use This Document",
            "",
            "### For AI Assistants",
            "- **Start here** when you need to find a component",
            "- **Check tier** before using (1 = safest, 4 = don't use)",
            "- **Look for alternatives** if component is deprecated",
            "",
            "### For Developers",
            "- **Quick reference** for component status",
            "- **Find examples** of correct usage patterns",
            "",
            "### For Updates",
            "Regenerate this file:",
            "```bash",
            "python tools/generate_working_code_index.py",
            "```",
            "",
            "---",
            "",
            "*This is a living document. It reflects current reality, not aspirational goals.*",
            "",
            f"**Next Update**: {datetime.now().strftime('%Y-%m-%d')} (or when significant changes occur)",
            "",
        ])
        
        return '\n'.join(lines)
    
    def run(self, output_file: Optional[Path] = None) -> None:
        """Generate component index."""
        print("=" * 60)
        print("COMPONENT INDEX GENERATOR")
        print("=" * 60)
        
        self.scan_imports()
        
        markdown = self.generate_markdown()
        
        if output_file:
            with open(output_file, 'w') as f:
                f.write(markdown)
            print(f"\n✅ Index written to: {output_file}")
        else:
            print("\n" + markdown)
        
        print("\n" + "=" * 60)
        print("✅ Generation complete")
        print("=" * 60)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate working code index (WHAT_WORKS_NOW.md)"
    )
    parser.add_argument(
        '--output', '-o',
        type=str,
        default="WHAT_WORKS_NOW.md",
        help='Output file (default: WHAT_WORKS_NOW.md)'
    )
    
    args = parser.parse_args()
    
    indexer = ComponentIndexer()
    output_path = Path(args.output)
    indexer.run(output_path)


if __name__ == "__main__":
    main()
